title: The First Symposium of Geometry and Statistics
description: Yanqi Lake Beijing Institute of Mathematical Sciences and Applications, Yau Center at Tsinghua University <br> Beijing July 23 - 25, 2023
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
site.github.is_project_page: false
